### ISSUE TITLE
A Question About Proposal Status Checking in Module.sol

### ISSUE THREAD

**Issue by fgh1999** [CodeforDAO/contracts#3]
https://github.com/CodeforDAO/contracts/blob/e6d820c3e60466fd834257aabc5ccc1ad9458bed/contracts/core/Module.sol#L201-L217

Hi. I wanna ask a question: why you wrote `_proposal.status != DataTypes.ProposalStatus.Executed` in Line 208? And why is it not written as sth. like `_proposal.status == DataTypes.ProposalStatus.Executed`?
You've said "It is not possible to cancel a proposal that has already been executed", so does it mean that: though the status has been changed, the proposal might have not been executed? Maybe I got misunderstanding in the underlying mechanisms in blockchain?

Thanks.

**Comment by guo-yu** [comment]
Thank you for the correction. This is a typo that was not detected because the cancel method of the module was not covered by the original test case.

I fixed this bug in this commit https://github.com/CodeforDAO/contracts/commit/eee3f9aa3360b10f0d99dc8d6a8f462e345ca35a

Will add a test for `Module.cancel()` in a later commit.
